import { createSlice } from "@reduxjs/toolkit";

const initialGamesState = {
  level: "all",
  games:[
    {
      id: 1,
      played: false,
      level: "all",
      notplayed: true,
      status: "locked",
      name: "Pair it Up",
      link: "/games/memoryflip",
      img: "https://cdn.pixabay.com/photo/2014/12/21/23/58/flamingos-576492_1280.png",
      rules: "Match all the pairs within the given time to win!"
    },

    {
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      id: 2,
      name: "Puzzle",
      link: "/games/puzzle",
      img: "https://cdn.pixabay.com/photo/2012/04/05/02/19/jigsaw-26002_1280.png",

    },
    {
      id: 3,
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      name: "Catch a Fruit",
      link: "/games/fruit-catcher",
      img: "https://cdn.pixabay.com/photo/2020/07/22/20/57/fruits-basket-5429751_1280.png",

      rules: "Catch as many falling fruits as you can within the time limit!",
    },
    {
      id: 4,
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      name: "Tap and Smile",
      link: "/games/emoji-game",
      img: "https://cdn.pixabay.com/photo/2020/02/09/09/38/smiley-4832492_1280.png",
      rules: "Tap the smiling emojis and avoid the sad ones for points!",
    },
    {
      id: 5,
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      name: "Tic Tac Toe",
      link: "/games/tic-tac-toe",
      img: "https://cdn.pixabay.com/photo/2023/01/22/23/16/tic-tac-toe-7737546_1280.jpg",
      video: "https://example.com/videos/tic-tac-toe.mp4",
      rules: "Get three in a row to win against your opponent!",
    },
    {
      id: 6,
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      name: "Snake",
      link: "/games/snake",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/snake.mp4",
      rules: "Eat food and grow, but don't hit the walls or yourself!",
    },
    {
      id: 7,
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      name: "Rock Paper Scissor",
      link: "/games/rock-paper-scissor",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/rock-paper-scissor.mp4",
      rules: "Choose rock, paper, or scissors and outsmart the computer!",
    },
    {
      id: 8,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Fluffy Bird",
      link: "/games/fluffy-bird",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/fluffy-bird.mp4",
      rules: "Tap to keep the bird flying and avoid the obstacles!",
    },
    {
      id: 9,
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      name: "2048",
      link: "/games/2048",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/2048.mp4",
      rules: "Combine tiles with the same numbers to reach 2048!",
    },
    {
      id: 10,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Sudoko",
      link: "/games/sudoko-easy",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/sudoko.mp4",
      rules: "Fill the grid with numbers 1-9 without repeating in rows, columns, or boxes!",
    },
    {
      id: 11,
      played: false,
      notplayed: true,
      level: "medium",
      status: "locked",
      name: "Sudoko",
      link: "/games/sudoko-medium",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/sudoko.mp4",
      rules: "Fill the grid with numbers 1-9 without repeating in rows, columns, or boxes!",
    },
    {
      id: 12,
      played: false,
      notplayed: true,
      status: "locked",
      level: "hard",
      name: "Madness",
      link: "/games/madness/hard",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/madness.mp4",
      rules: "Survive the chaos and complete objectives to win!",
    },
    {
      id: 13,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Madness",
      link: "/games/madness/easy",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/madness.mp4",
      rules: "Survive the chaos and complete objectives to win!",
    },
    {
      id: 14,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Madness",
      link: "/games/madness/medium",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/madness.mp4",
      rules: "Survive the chaos and complete objectives to win!",
    },
    {
      id: 15,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Matching Game",
      link: "/games/matching/animal",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 16,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Matching Game",
      link: "/games/matching/cars",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 17,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Matching Game",
      link: "/games/matching/fruits",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 18,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Matching Game",
      link: "/games/matching/vegetables",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 19,
      played: false,
      notplayed: true,
      level: "hard",
      status: "locked",
      name: "Matching Game",
      link: "/games/matching/flags",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 20,
      played: false,
      notplayed: true,
      level: "hard",
      status: "locked",
      name: "Matching Game",
      link: "/games/matching/planets",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 21,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Matching Game",
      link: "/games/matching/products",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 22,
      played: false,
      notplayed: true,
      status: "locked",
      level: "hard",
      name: "Matching Game",
      link: "/games/matching/professions",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 23,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Matching Game",
      link: "/games/matching/sports",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 24,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Spot Differences",
      link: "/games/differences",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/spot-differences.mp4",
      rules: "Spot all the differences between two pictures!",
    },
    {
      id: 25,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Shadow Game",
      link: "/games/shadow-game",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/shadow-game.mp4",
      rules: "Match the objects with their shadows before time runs out!",
    },
    {
      id: 26,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Finding Word",
      link: "/games/dots-game",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/finding-word.mp4",
      rules: "Find all the hidden words to solve the puzzle and score points!",
    },
    {
      id: 27,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Guess Number",
      link: "/games/tooth-defender",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/guess-number.mp4",
      rules: "Guess the number chosen by the computer in the least attempts!",
    },
    {
      id: 28,
      played: false,
      notplayed: true,
      status: "locked",
      name: "Maths Quiz",
      level: "easy",
      link: "/games/maths-quiz-easy",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/maths-quiz.mp4",
      rules: "Answer math questions quickly to earn points!",
    },
    {
      id: 29,
      played: false,
      notplayed: true,
      status: "locked",
      name: "Maths Quiz",
      level: "medium",
      link: "/games/maths-quiz-medium",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/maths-quiz.mp4",
      rules: "Answer math questions quickly to earn points!",
    },
    {
      id: 30,
      played: false,
      notplayed: true,
      status: "locked",
      name: "Maths Quiz",
      level: "hard",
      link: "/games/maths-quiz-hard",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/maths-quiz.mp4",
      rules: "Answer math questions quickly to earn points!",
    },
    {
      id: 31,
      played: false,
      notplayed: true,
      status: "locked",
      name: "Missing Number",
      level: "all",
      link: "/games/missing-number",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/missing-number.mp4",
      rules: "Fill in the missing number to complete the sequence!",
    },
    {
      id: 32,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Odd One Out",
      link: "/games/odd-one-out-animal",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 33,
      played: false,
      notplayed: true,
      level: "medium",
      status: "locked",
      name: "Odd One Out",
      link: "/games/odd-one-out-entertainment",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 34,
      played: false,
      notplayed: true,
      level: "medium",
      status: "locked",
      name: "Odd One Out",
      link: "/games/odd-one-out-festive",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 35,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Odd One Out",
      link: "/games/odd-one-out-food",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 36,
      played: false,
      notplayed: true,
      status: "locked",
      level: "hard",
      name: "Odd One Out",
      link: "/games/odd-one-out-profession",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 37,
      played: false,
      notplayed: true,
      status: "locked",
      name: "Odd One Out",
      level: "medium",
      link: "/games/odd-one-out-sports",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 38,
      played: false,
      notplayed: true,
      status: "locked",
      level: "hard",
      name: "Odd One Out",
      link: "/games/odd-one-out-travel",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 39,
      played: false,
      notplayed: true,
      level: "hard",
      status: "locked",
      name: "Odd One Out-wheather",
      link: "/games/odd-one-out",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 40,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Odd One Out",
      link: "/games/odd-one-out-main",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 41,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Reorder It",
      link: "/games/reorder-it-easy-1",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 42,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Reorder It",
      link: "/games/reorder-it-easy-2",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 43,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Reorder It",
      link: "/games/reorder-it-easy-3",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 44,
      played: false,
      notplayed: true,
      level: "medium",
      status: "locked",
      name: "Reorder It",
      link: "/games/reorder-it-medium-1",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 45,
      played: false,
      notplayed: true,
      level: "medium",
      status: "locked",
      name: "Reorder It",
      link: "/games/reorder-it-medium-2",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 46,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Reorder It",
      link: "/games/reorder-it-medium-3",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 47,
      played: false,
      notplayed: true,
      level: "hard",
      status: "locked",
      name: "Reorder It",
      link: "/games/reorder-it-hard-1",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 48,
      played: false,
      notplayed: true,
      status: "locked",
      level: "hard",
      name: "Reorder It",
      link: "/games/reorder-it-hard-2",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 49,
      played: false,
      level: "hard",
      notplayed: true,
      status: "locked",
      name: "Reorder It",
      link: "/games/reorder-it-hard-3",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 50,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Find It",
      link: "/games/findIt/easy/1",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 51,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Find It",
      link: "/games/findIt/easy/2",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 52,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Find It",
      link: "/games/findIt/easy/3",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 53,
      played: false,
      level: "medium",
      notplayed: true,
      status: "locked",
      name: "Find It",
      link: "/games/findIt/medium/1",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 54,
      played: false,
      level: "medium",
      notplayed: true,
      status: "locked",
      name: "Find It",
      link: "/games/findIt/medium/2",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 55,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Find It",
      link: "/games/findIt/medium/3",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 56,
      played: false,
      notplayed: true,
      level: "hard",
      status: "locked",
      name: "Find It",
      link: "/games/findIt/hard/1",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 57,
      played: false,
      level: "hard",
      notplayed: true,
      status: "locked",
      name: "Find It",
      link: "/games/findIt/hard/2",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 58,
      played: false,
      notplayed: true,
      level: "hard",
      status: "locked",
      name: "Find It",
      link: "/games/findIt/hard/3",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 59,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-easy-1",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 60,
      played: false,
      level: "easy",
      notplayed: true,
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-easy-2",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 61,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-easy-3",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 62,
      played: false,
      notplayed: true,
      level: "medium",
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-medium-1",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 63,
      played: false,
      level: "medium",
      notplayed: true,
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-medium-2",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 64,
      played: false,
      level: "medium",
      notplayed: true,
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-medium-3",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 65,
      played: false,
      level: "hard",
      notplayed: true,
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-hard-1",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 66,
      played: false,
      level: "hard",
      notplayed: true,
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-hard-2",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 67,
      played: false,
      notplayed: true,
      level: "hard",
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-hard-3",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 68,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Number Pattern",
      link: "/games/number-pattern-easy",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/number-pattern.mp4",
      rules: "Identify and complete the number patterns in the grid!",
    },
    {
      id: 69,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Number Pattern",
      link: "/games/number-pattern-medium",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/number-pattern.mp4",
      rules: "Identify and complete the number patterns in the grid!",
    },
    {
      id: 70,
      played: false,
      notplayed: true,
      status: "locked",
      level: "hard",
      name: "Number Pattern",
      link: "/games/number-pattern-hard",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/number-pattern.mp4",
      rules: "Identify and complete the number patterns in the grid!",
    },
    {
      id: 71,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Moon Activity",
      link: "/games/moon-game",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/moon-activity.mp4",
      rules: "Perform actions related to the moon phases and earn points!",
    },
    {
      id: 72,
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      name: "Monkey",
      link: "/games/monkey-game",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/monkey-game.mp4",
      rules: "Help the monkey collect bananas and avoid obstacles!",
    },
    {
      id: 73,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Bodmas Maths",
      link: "/games/bodmas-maths",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/bodmas-maths.mp4",
      rules: "Solve equations using BODMAS rules to score points!",
    },
    {
      id: 74,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Quick Tap",
      link: "/games/quick-tap",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/quick-tap.mp4",
      rules: "Tap quickly on the targets to earn points before time runs out!",
    },
    {
      id: 75,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Image Suspense",
      link: "/games/image-suspense",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/image-suspense.mp4",
      rules: "Unveil the hidden image piece by piece before time runs out!",
    },
    {
      id: 76,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Spin Wheel",
      link: "/games/spin-wheel",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/spin-wheel.mp4",
      rules: "Spin the wheel and complete challenges to win rewards!",
    },
    {
      id: 77,
      played: false,
      notplayed: true,
      status: "locked",
      level: "hard",
      name: "Spin Math",
      link: "/games/spin-math-hard",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/spin-math.mp4",
      rules: "Spin the wheel to get math questions and solve them to score points!",
    },
    {
      id: 78,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Spin Math",
      link: "/games/spin-math-easy",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/spin-math.mp4",
      rules: "Spin the wheel to get math questions and solve them to score points!",
    },
    {
      id: 79,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Spin Math",
      link: "/games/spin-math-medium",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/spin-math.mp4",
      rules: "Spin the wheel to get math questions and solve them to score points!",
    }
  ]
};

const gamesSlice = createSlice({
  name: "games",
  initialState: initialGamesState,
  reducers: {

    updateGameStatus(state, action) {
      const { id, status } = action.payload;
      const game = state.games.find((game) => game.id === id);
      if (game) {
        game.status = status;
        game.played = status === "played";
        game.notplayed = status !== "played";
      }
    },
    unlockRandomGame(state) {
      const currentLevel = state.level;

      const lockedGames = state.games.filter(
        (game) =>
          game.status === "locked" &&
          (game.level === currentLevel || game.level === "all")
      );

      if (lockedGames.length > 0) {
        const randomIndex = Math.floor(Math.random() * lockedGames.length);
        const gameToUnlock = lockedGames[randomIndex];
        gameToUnlock.status = "unlocked";
        gameToUnlock.notplayed = true;
      }
    },
    markGameAsPlayed(state, action) {
      const gameId = action.payload;
      const game = state.games.find((game) => game.id === gameId);
    
      // Debug log
      console.log('Before update:', game);
    
      if (game && !game.played) {
        game.played = true;
        game.status = "played";
    
        // Debug log after updating
        console.log('After update:', game);
      }
    },
    updateLevel(state, action) {
      console.log("Level updated to:", action.payload);
      state.level = action.payload;
    },
  },
});

export const { updateGameStatus, unlockRandomGame, markGameAsPlayed, updateLevel } =
  gamesSlice.actions;

export default gamesSlice.reducer;
