import { createSlice } from "@reduxjs/toolkit";

const initialGamesState = {
  level: "all",
  games:[
    {
      id: 1,
      played: false,
      level: "all",
      notplayed: true,
      status: "locked",
      name: "Pair it Up",
      link: "/games/memoryflip",
      img: "https://cdn.pixabay.com/photo/2014/12/21/23/58/flamingos-576492_1280.png",
      rules: "Match all the pairs within the given time to win!"
    },

    {
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      id: 2,
      name: "Puzzle",
      link: "/games/puzzle",
      img: "https://cdn.pixabay.com/photo/2012/04/05/02/19/jigsaw-26002_1280.png",

    },
    {
      id: 3,
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      name: "Catch a Fruit",
      link: "/games/fruit-catcher",
      img: "https://cdn.pixabay.com/photo/2020/07/22/20/57/fruits-basket-5429751_1280.png",

      rules: "Catch as many falling fruits as you can within the time limit!",
    },
    {
      id: 4,
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      name: "Tap and Smile",
      link: "/games/emoji-game",
      img: "https://cdn.pixabay.com/photo/2020/02/09/09/38/smiley-4832492_1280.png",
      rules: "Tap the smiling emojis and avoid the sad ones for points!",
    },
    {
      id: 5,
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      name: "Tic Tac Toe",
      link: "/games/tic-tac-toe",
      img: "https://cdn.pixabay.com/photo/2023/01/22/23/16/tic-tac-toe-7737546_1280.jpg",
      video: "https://example.com/videos/tic-tac-toe.mp4",
      rules: "Get three in a row to win against your opponent!",
    },
    {
      id: 6,
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      name: "Snake",
      link: "/games/snake",
      img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
      video: "https://example.com/videos/snake.mp4",
      rules: "Eat food and grow, but don't hit the walls or yourself!",
    },
    {
      id: 7,
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      name: "Rock Paper Scissor",
      link: "/games/rock-paper-scissor",
      img: "https://w7.pngwing.com/pngs/378/463/png-transparent-rock-paper-scissors-game-money-scissors-text-dragon-hand-thumbnail.png",
      video: "https://example.com/videos/rock-paper-scissor.mp4",
      rules: "Choose rock, paper, or scissors and outsmart the computer!",
    },
    {
      id: 8,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Fluffy Bird",
      link: "/games/fluffy-bird",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQOJewP1zEFKny5Y3YSETAg-PglWTaREe5qg&s",
      video: "https://example.com/videos/fluffy-bird.mp4",
      rules: "Tap to keep the bird flying and avoid the obstacles!",
    },
    {
      id: 9,
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      name: "2048",
      link: "/games/2048",
      img: "https://w7.pngwing.com/pngs/954/902/png-transparent-2048-art-area-text-symbol-number-apps-2048-game-text-logo-thumbnail.png",
      video: "https://example.com/videos/2048.mp4",
      rules: "Combine tiles with the same numbers to reach 2048!",
    },
    {
      id: 10,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Sudoko",
      link: "/games/sudoko-easy",
      img: "https://w7.pngwing.com/pngs/287/785/png-transparent-free-sudoku-game-sudoku-2-best-sudoku-solve-sudoku-android-purple-game-text-thumbnail.png",
      video: "https://example.com/videos/sudoko.mp4",
      rules: "Fill the grid with numbers 1-9 without repeating in rows, columns, or boxes!",
    },
    {
      id: 11,
      played: false,
      notplayed: true,
      level: "medium",
      status: "locked",
      name: "Sudoko",
      link: "/games/sudoko-medium",
      img: "https://w7.pngwing.com/pngs/287/785/png-transparent-free-sudoku-game-sudoku-2-best-sudoku-solve-sudoku-android-purple-game-text-thumbnail.png",
      video: "https://example.com/videos/sudoko.mp4",
      rules: "Fill the grid with numbers 1-9 without repeating in rows, columns, or boxes!",
    },
    {
      id: 12,
      played: false,
      notplayed: true,
      status: "locked",
      level: "hard",
      name: "Madness",
      link: "/games/madness/hard",
      img: "https://w7.pngwing.com/pngs/643/208/png-transparent-mathematics-question-situation-puzzle-number-logic-homero-game-child-face-thumbnail.png",
      video: "https://example.com/videos/madness.mp4",
      rules: "Survive the chaos and complete objectives to win!",
    },
    {
      id: 13,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Madness",
      link: "/games/madness/easy",
      img: "https://w7.pngwing.com/pngs/643/208/png-transparent-mathematics-question-situation-puzzle-number-logic-homero-game-child-face-thumbnail.png",
      video: "https://example.com/videos/madness.mp4",
      rules: "Survive the chaos and complete objectives to win!",
    },
    {
      id: 14,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Madness",
      link: "/games/madness/medium",
      img: "https://w7.pngwing.com/pngs/643/208/png-transparent-mathematics-question-situation-puzzle-number-logic-homero-game-child-face-thumbnail.png",
      video: "https://example.com/videos/madness.mp4",
      rules: "Survive the chaos and complete objectives to win!",
    },
    {
      id: 15,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Matching Game",
      link: "/games/matching/animal",
      img: "https://w7.pngwing.com/pngs/775/408/png-transparent-cartoon-animal-cartoon-animal-photography-wildlife-cartoon-thumbnail.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 16,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Matching Game",
      link: "/games/matching/cars",
      img: "https://w7.pngwing.com/pngs/817/252/png-transparent-enterprise-rent-a-car-vehicle-car-rental-carsharing-car-compact-car-truck-car-thumbnail.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 17,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Matching Game",
      link: "/games/matching/fruits",
      img: "https://w7.pngwing.com/pngs/643/19/png-transparent-fruit-fruit-miscellaneous-natural-foods-food-thumbnail.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 18,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Matching Game",
      link: "/games/matching/vegetables",
      img: "https://w7.pngwing.com/pngs/747/590/png-transparent-vegetable-fruit-food-allergy-eating-vegetables-and-fruits-heap-natural-foods-leaf-vegetable-food-thumbnail.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 19,
      played: false,
      notplayed: true,
      level: "hard",
      status: "locked",
      name: "Matching Game",
      link: "/games/matching/flags",
      img: "https://w7.pngwing.com/pngs/566/173/png-transparent-national-flags-themed-planet-illustration-globe-flags-of-the-world-world-flag-flag-flag-countries-flags-spherical-miscellaneous-flag-symmetry-thumbnail.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 20,
      played: false,
      notplayed: true,
      level: "hard",
      status: "locked",
      name: "Matching Game",
      link: "/games/matching/planets",
      img: "https://w7.pngwing.com/pngs/773/95/png-transparent-8-assorted-planets-and-sun-illustration-planet-mercury-venus-euclidean-planet-miscellaneous-globe-orange-thumbnail.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 21,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Matching Game",
      link: "/games/matching/products",
      img: "https://w7.pngwing.com/pngs/1013/766/png-transparent-movie-products-illustration-video-production-production-companies-flat-design-production-television-web-design-film-thumbnail.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 22,
      played: false,
      notplayed: true,
      status: "locked",
      level: "hard",
      name: "Matching Game",
      link: "/games/matching/professions",
      img: "https://w7.pngwing.com/pngs/241/819/png-transparent-job-profession-profession-miscellaneous-cartoon-fictional-character-thumbnail.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 23,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Matching Game",
      link: "/games/matching/sports",
      img: "https://w7.pngwing.com/pngs/301/620/png-transparent-sport-kids-sports-miscellaneous-child-hand-thumbnail.png",
      video: "https://example.com/videos/matching-game.mp4",
      rules: "Find and match all pairs to win!",
    },
    {
      id: 24,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Spot Differences",
      link: "/games/differences",
      img: "https://w7.pngwing.com/pngs/44/174/png-transparent-spot-the-difference-word-connection-puzzle-game-word-market-find-the-difference-v30-spot-the-difference-game-free-spot-the-difference-blue-text-logo-thumbnail.png",
      video: "https://example.com/videos/spot-differences.mp4",
      rules: "Spot all the differences between two pictures!",
    },
    {
      id: 25,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Shadow Game",
      link: "/games/shadow-game",
      img: "https://w7.pngwing.com/pngs/88/625/png-transparent-rabbit-silhouette-black-isolated-form-animal-shadow-thumbnail.png",
      video: "https://example.com/videos/shadow-game.mp4",
      rules: "Match the objects with their shadows before time runs out!",
    },
    {
      id: 26,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Finding Word",
      link: "/games/dots-game",
      img: "https://w7.pngwing.com/pngs/448/64/png-transparent-word-to-word-association-game-infinite-word-search-puzzles-word-search-and-find-word-search-find-word-search-crossword-finder-word-blue-game-text-thumbnail.png",
      video: "https://example.com/videos/finding-word.mp4",
      rules: "Find all the hidden words to solve the puzzle and score points!",
    },
    {
      id: 27,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Guess Number",
      link: "/games/tooth-defender",
      img: "https://w7.pngwing.com/pngs/19/677/png-transparent-guess-the-number-game-android-bengali-android-game-text-logo-thumbnail.png",
      video: "https://example.com/videos/guess-number.mp4",
      rules: "Guess the number chosen by the computer in the least attempts!",
    },
    {
      id: 28,
      played: false,
      notplayed: true,
      status: "locked",
      name: "Maths Quiz",
      level: "easy",
      link: "/games/maths-quiz-easy",
      img: "https://w7.pngwing.com/pngs/40/4/png-transparent-symbol-line-maths-thumbnail.png",
      video: "https://example.com/videos/maths-quiz.mp4",
      rules: "Answer math questions quickly to earn points!",
    },
    {
      id: 29,
      played: false,
      notplayed: true,
      status: "locked",
      name: "Maths Quiz",
      level: "medium",
      link: "/games/maths-quiz-medium",
      img: "https://w7.pngwing.com/pngs/539/31/png-transparent-mathematics-math-mammal-food-cat-like-mammal-thumbnail.png",
      video: "https://example.com/videos/maths-quiz.mp4",
      rules: "Answer math questions quickly to earn points!",
    },
    {
      id: 30,
      played: false,
      notplayed: true,
      status: "locked",
      name: "Maths Quiz",
      level: "hard",
      link: "/games/maths-quiz-hard",
      img: "https://w7.pngwing.com/pngs/751/542/png-transparent-mathematics-child-learning-brain-math-text-computer-presentation-thumbnail.png",
      video: "https://example.com/videos/maths-quiz.mp4",
      rules: "Answer math questions quickly to earn points!",
    },
    {
      id: 31,
      played: false,
      notplayed: true,
      status: "locked",
      name: "Missing Number",
      level: "all",
      link: "/games/missing-number",
      img: "https://w7.pngwing.com/pngs/732/841/png-transparent-game-cartoon-frames-wood-m-083vt-wood-thumbnail.png",
      video: "https://example.com/videos/missing-number.mp4",
      rules: "Fill in the missing number to complete the sequence!",
    },
    {
      id: 32,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Odd One Out",
      link: "/games/odd-one-out-animal",
      img: "https://w7.pngwing.com/pngs/465/433/png-transparent-giraffe-infant-illustration-animal-assorted-animated-animals-illustration-child-mammal-cat-like-mammal-thumbnail.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 33,
      played: false,
      notplayed: true,
      level: "medium",
      status: "locked",
      name: "Odd One Out",
      link: "/games/odd-one-out-entertainment",
      img: "https://w7.pngwing.com/pngs/695/667/png-transparent-entertainment-traveling-carnival-fair-city-entertainment-purple-violet-text-thumbnail.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 34,
      played: false,
      notplayed: true,
      level: "medium",
      status: "locked",
      name: "Odd One Out",
      link: "/games/odd-one-out-festive",
      img: "https://w7.pngwing.com/pngs/428/191/png-transparent-garland-christmas-red-festive-leaf-decor-heart-thumbnail.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 35,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Odd One Out",
      link: "/games/odd-one-out-food",
      img: "https://w7.pngwing.com/pngs/686/527/png-transparent-fast-food-hamburger-sushi-pizza-fast-food-food-breakfast-fast-food-restaurant-thumbnail.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 36,
      played: false,
      notplayed: true,
      status: "locked",
      level: "hard",
      name: "Odd One Out",
      link: "/games/odd-one-out-profession",
      img: "https://w7.pngwing.com/pngs/470/64/png-transparent-profession-programmer-job-fachgebiet-career-counseling-profession-service-team-engineer-thumbnail.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 37,
      played: false,
      notplayed: true,
      status: "locked",
      name: "Odd One Out",
      level: "medium",
      link: "/games/odd-one-out-sports",
      img: "https://w7.pngwing.com/pngs/449/830/png-transparent-baseball-sporting-goods-sports-association-sports-activities-sport-orange-fashion-thumbnail.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 38,
      played: false,
      notplayed: true,
      status: "locked",
      level: "hard",
      name: "Odd One Out",
      link: "/games/odd-one-out-travel",
      img: "https://w7.pngwing.com/pngs/791/242/png-transparent-world-travel-illustration-world-map-globe-travel-global-travel-logo-computer-wallpaper-world-thumbnail.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 39,
      played: false,
      notplayed: true,
      level: "hard",
      status: "locked",
      name: "Odd One Out-wheather",
      link: "/games/odd-one-out",
      img: "https://w7.pngwing.com/pngs/760/237/png-transparent-weather-and-climate-weather-and-climate-weather-radar-weather-station-weather-leaf-logo-weather-forecasting-thumbnail.png",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 40,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Odd One Out",
      link: "/games/odd-one-out-main",
      img: "https://th.bing.com/th/id/R.aea51d580b6e16886c8e2107cf8c5b3a?rik=XCxDOgHvjIcGAQ&riu=http%3a%2f%2fwww.megaworkbook.com%2fimages%2fcontent%2fGeneralAptitude%2fOddOneOut%2fOdd_one_out_04.png&ehk=IFE29fODqsgSG4srz6dEy1cQzMcdoOE%2fzRhyInqgRuQ%3d&risl=&pid=ImgRaw&r=0",
      video: "https://example.com/videos/odd-one-out.mp4",
      rules: "Find the object that doesn't belong in the group!",
    },
    {
      id: 41,
      played: false,
      notplayed: true,
      status: "locked",
      level: "easy",
      name: "Reorder It",
      link: "/games/reorder-it-easy-1",
      img: "https://w7.pngwing.com/pngs/961/904/png-transparent-emoji-video-game-sms-games-game-sticker-joystick-thumbnail.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 42,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Reorder It",
      link: "/games/reorder-it-easy-2",
      img: "https://w7.pngwing.com/pngs/305/775/png-transparent-arrow-change-start-new-beginning-beginning-begin-renewal-innovation-novelty-reordering-thumbnail.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 43,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Reorder It",
      link: "/games/reorder-it-easy-3",
      img: "https://w7.pngwing.com/pngs/392/758/png-transparent-change-new-beginning-renewal-innovation-novelty-reordering-new-rules-reform-reorganization-transformation-thumbnail.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 44,
      played: false,
      notplayed: true,
      level: "medium",
      status: "locked",
      name: "Reorder It",
      link: "/games/reorder-it-medium-1",
      img: "https://w7.pngwing.com/pngs/961/904/png-transparent-emoji-video-game-sms-games-game-sticker-joystick-thumbnail.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 45,
      played: false,
      notplayed: true,
      level: "medium",
      status: "locked",
      name: "Reorder It",
      link: "/games/reorder-it-medium-2",
      img: "https://w7.pngwing.com/pngs/305/775/png-transparent-arrow-change-start-new-beginning-beginning-begin-renewal-innovation-novelty-reordering-thumbnail.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 46,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Reorder It",
      link: "/games/reorder-it-medium-3",
      img: "https://w7.pngwing.com/pngs/392/758/png-transparent-change-new-beginning-renewal-innovation-novelty-reordering-new-rules-reform-reorganization-transformation-thumbnail.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 47,
      played: false,
      notplayed: true,
      level: "hard",
      status: "locked",
      name: "Reorder It",
      link: "/games/reorder-it-hard-1",
      img: "https://w7.pngwing.com/pngs/961/904/png-transparent-emoji-video-game-sms-games-game-sticker-joystick-thumbnail.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 48,
      played: false,
      notplayed: true,
      status: "locked",
      level: "hard",
      name: "Reorder It",
      link: "/games/reorder-it-hard-2",
      img: "https://w7.pngwing.com/pngs/305/775/png-transparent-arrow-change-start-new-beginning-beginning-begin-renewal-innovation-novelty-reordering-thumbnail.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 49,
      played: false,
      level: "hard",
      notplayed: true,
      status: "locked",
      name: "Reorder It",
      link: "/games/reorder-it-hard-3",
      img: "https://w7.pngwing.com/pngs/392/758/png-transparent-change-new-beginning-renewal-innovation-novelty-reordering-new-rules-reform-reorganization-transformation-thumbnail.png",
      video: "https://example.com/videos/reorder-it.mp4",
      rules: "Rearrange the pieces to form the correct sequence or image!",
    },
    {
      id: 50,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Find It",
      link: "/games/findIt/easy/1",
      img: "https://c8.alamy.com/comp/D28MC6/refrigerator-magnet-letters-jumbled-up-in-a-random-pattern-D28MC6.jpg",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 51,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Find It",
      link: "/games/findIt/easy/2",
      img: "https://th.bing.com/th/id/OIP.SPavQGhF9t4W7rObgW1SKQHaEK?w=297&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 52,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Find It",
      link: "/games/findIt/easy/3",
      img: "https://i.pinimg.com/originals/f3/19/13/f31913679282ad00ca8effcfd86b73d2.jpg",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 53,
      played: false,
      level: "medium",
      notplayed: true,
      status: "locked",
      name: "Find It",
      link: "/games/findIt/medium/1",
      img: "https://c8.alamy.com/comp/D28MC6/refrigerator-magnet-letters-jumbled-up-in-a-random-pattern-D28MC6.jpg",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 54,
      played: false,
      level: "medium",
      notplayed: true,
      status: "locked",
      name: "Find It",
      link: "/games/findIt/medium/2",
      img: "https://th.bing.com/th/id/OIP.SPavQGhF9t4W7rObgW1SKQHaEK?w=297&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 55,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Find It",
      link: "/games/findIt/medium/3",
      img: "https://i.pinimg.com/originals/f3/19/13/f31913679282ad00ca8effcfd86b73d2.jpg",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 56,
      played: false,
      notplayed: true,
      level: "hard",
      status: "locked",
      name: "Find It",
      link: "/games/findIt/hard/1",
      img: "https://c8.alamy.com/comp/D28MC6/refrigerator-magnet-letters-jumbled-up-in-a-random-pattern-D28MC6.jpg",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 57,
      played: false,
      level: "hard",
      notplayed: true,
      status: "locked",
      name: "Find It",
      link: "/games/findIt/hard/2",
      img: "https://th.bing.com/th/id/OIP.SPavQGhF9t4W7rObgW1SKQHaEK?w=297&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 58,
      played: false,
      notplayed: true,
      level: "hard",
      status: "locked",
      name: "Find It",
      link: "/games/findIt/hard/3",
      img: "https://i.pinimg.com/originals/f3/19/13/f31913679282ad00ca8effcfd86b73d2.jpg",
      video: "https://example.com/videos/find-it.mp4",
      rules: "Search and find all the hidden objects in the scene!",
    },
    {
      id: 59,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-easy-1",
      img: "https://th.bing.com/th/id/OIP.QISNqvjrPehVXzGtn-e64AHaHa?w=202&h=202&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 60,
      played: false,
      level: "easy",
      notplayed: true,
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-easy-2",
      img: "https://img.freepik.com/premium-vector/write-missing-letter_74440-221.jpg",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 61,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-easy-3",
      img: "https://th.bing.com/th/id/OIP.HA_B-1dU74LytbgI2xH-cQHaFu?w=202&h=156&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 62,
      played: false,
      notplayed: true,
      level: "medium",
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-medium-1",
      img: "https://th.bing.com/th/id/OIP.QISNqvjrPehVXzGtn-e64AHaHa?w=202&h=202&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 63,
      played: false,
      level: "medium",
      notplayed: true,
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-medium-2",
      img: "https://img.freepik.com/premium-vector/write-missing-letter_74440-221.jpg",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 64,
      played: false,
      level: "medium",
      notplayed: true,
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-medium-3",
      img: "https://th.bing.com/th/id/OIP.HA_B-1dU74LytbgI2xH-cQHaFu?w=202&h=156&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 65,
      played: false,
      level: "hard",
      notplayed: true,
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-hard-1",
      img: "https://th.bing.com/th/id/OIP.QISNqvjrPehVXzGtn-e64AHaHa?w=202&h=202&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 66,
      played: false,
      level: "hard",
      notplayed: true,
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-hard-2",
      img: "https://img.freepik.com/premium-vector/write-missing-letter_74440-221.jpg",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 67,
      played: false,
      notplayed: true,
      level: "hard",
      status: "locked",
      name: "Missing Letter",
      link: "/games/missing-letter-hard-3",
      img: "https://th.bing.com/th/id/OIP.HA_B-1dU74LytbgI2xH-cQHaFu?w=202&h=156&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      video: "https://example.com/videos/missing-letter.mp4",
      rules: "Guess the missing letters to complete the word!",
    },
    {
      id: 68,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Number Pattern",
      link: "/games/number-pattern-easy",
      img: "https://www.splashlearn.com/math-vocabulary/wp-content/uploads/2023/01/What-is-Number-Patterns-2.png",
      video: "https://example.com/videos/number-pattern.mp4",
      rules: "Identify and complete the number patterns in the grid!",
    },
    {
      id: 69,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Number Pattern",
      link: "/games/number-pattern-medium",
      img: "https://i.ytimg.com/vi/GcoDAdTizoQ/maxresdefault.jpg",
      video: "https://example.com/videos/number-pattern.mp4",
      rules: "Identify and complete the number patterns in the grid!",
    },
    {
      id: 70,
      played: false,
      notplayed: true,
      status: "locked",
      level: "hard",
      name: "Number Pattern",
      link: "/games/number-pattern-hard",
      img: "https://th.bing.com/th/id/OIP.gHpSfXQNzf90xtLM6iqgZQHaHa?w=202&h=202&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      video: "https://example.com/videos/number-pattern.mp4",
      rules: "Identify and complete the number patterns in the grid!",
    },
    {
      id: 71,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Moon Activity",
      link: "/games/moon-game",
      img: "https://th.bing.com/th/id/OIP.nVik1_mnIHCen9_8--snKQHaJV?w=202&h=255&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      video: "https://example.com/videos/moon-activity.mp4",
      rules: "Perform actions related to the moon phases and earn points!",
    },
    {
      id: 72,
      played: false,
      notplayed: true,
      level: "all",
      status: "locked",
      name: "Monkey",
      link: "/games/monkey-game",
      img: "https://w7.pngwing.com/pngs/946/734/png-transparent-monkey-graphics-illustration-monkey-banana-monkey-mammal-animals-carnivoran-thumbnail.png",
      video: "https://example.com/videos/monkey-game.mp4",
      rules: "Help the monkey collect bananas and avoid obstacles!",
    },
    // {
    //   id: 73,
    //   played: false,
    //   notplayed: true,
    //   status: "locked",
    //   level: "all",
    //   name: "Bodmas Maths",
    //   link: "/games/bodmas-maths",
    //   img: "https://cdn.pixabay.com/photo/2013/07/13/13/42/snake-161424_1280.png",
    //   video: "https://example.com/videos/bodmas-maths.mp4",
    //   rules: "Solve equations using BODMAS rules to score points!",
    // },
    {
      id: 73,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Quick Tap",
      link: "/games/quick-tap",
      img: "https://th.bing.com/th/id/OIP.DFweLsu3drHvv3WNQ0kQwwHaFQ?w=252&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      video: "https://example.com/videos/quick-tap.mp4",
      rules: "Tap quickly on the targets to earn points before time runs out!",
    },
    {
      id: 74,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Image Suspense",
      link: "/games/image-suspense",
      img: "https://th.bing.com/th/id/OIP.JPaIzWZUkHe98pflNTut4wHaHa?w=193&h=193&c=7&r=0&o=5&dpr=1.5&pid=1.7",
      video: "https://example.com/videos/image-suspense.mp4",
      rules: "Unveil the hidden image piece by piece before time runs out!",
    },
    {
      id: 75,
      played: false,
      notplayed: true,
      status: "locked",
      level: "all",
      name: "Spin Wheel",
      link: "/games/spin-wheel",
      img: "https://w7.pngwing.com/pngs/723/282/png-transparent-spin-the-wheel-spinning-wheel-spinning-wheel-game-thumbnail.png",
      video: "https://example.com/videos/spin-wheel.mp4",
      rules: "Spin the wheel and complete challenges to win rewards!",
    },
    {
      id: 76,
      played: false,
      notplayed: true,
      status: "locked",
      level: "hard",
      name: "Spin Math",
      link: "/games/spin-math-hard",
      img: "https://thumbs.dreamstime.com/b/color-lucky-wheel-icon-flat-style-color-lucky-wheel-icon-flat-illustration-color-lucky-wheel-icon-web-design-124510313.jpg",
      video: "https://example.com/videos/spin-math.mp4",
      rules: "Spin the wheel to get math questions and solve them to score points!",
    },
    {
      id: 77,
      played: false,
      notplayed: true,
      level: "easy",
      status: "locked",
      name: "Spin Math",
      link: "/games/spin-math-easy",
      img: "https://thumbs.dreamstime.com/b/color-lucky-wheel-icon-flat-style-color-lucky-wheel-icon-flat-illustration-color-lucky-wheel-icon-web-design-124510313.jpg",
      video: "https://example.com/videos/spin-math.mp4",
      rules: "Spin the wheel to get math questions and solve them to score points!",
    },
    {
      id: 78,
      played: false,
      notplayed: true,
      status: "locked",
      level: "medium",
      name: "Spin Math",
      link: "/games/spin-math-medium",
      img: "https://thumbs.dreamstime.com/b/color-lucky-wheel-icon-flat-style-color-lucky-wheel-icon-flat-illustration-color-lucky-wheel-icon-web-design-124510313.jpg",
      video: "https://example.com/videos/spin-math.mp4",
      rules: "Spin the wheel to get math questions and solve them to score points!",
    }
  ]
};

const gamesSlice = createSlice({
  name: "games",
  initialState: initialGamesState,
  reducers: {

    updateGameStatus(state, action) {
      const { id, status } = action.payload;
      const game = state.games.find((game) => game.id === id);
      if (game) {
        game.status = status;
        game.played = status === "played";
        game.notplayed = status !== "played";
      }
    },
    unlockRandomGame(state) {
      const currentLevel = state.level;

      const lockedGames = state.games.filter(
        (game) =>
          game.status === "locked" &&
          (game.level === currentLevel || game.level === "all")
      );

      if (lockedGames.length > 0) {
        const randomIndex = Math.floor(Math.random() * lockedGames.length);
        const gameToUnlock = lockedGames[randomIndex];
        gameToUnlock.status = "unlocked";
        gameToUnlock.notplayed = true;
      }
    },
    markGameAsPlayed(state, action) {
      const gameId = action.payload;
      const game = state.games.find((game) => game.id === gameId);
    
      // Debug log
      console.log('Before update:', game);
    
      if (game && !game.played) {
        game.played = true;
        game.status = "played";
    
        // Debug log after updating
        console.log('After update:', game);
      }
    },
    updateLevel(state, action) {
      console.log("Level updated to:", action.payload);
      state.level = action.payload;
    },
  },
});

export const { updateGameStatus, unlockRandomGame, markGameAsPlayed, updateLevel } =
  gamesSlice.actions;

export default gamesSlice.reducer;
